### ISSUE TITLE
--strictness level ordering

### ISSUE THREAD

**Issue by gambogi** [landscapeio/prospector#133]
Tried the tool out for the first time today. Ran it with `--strictness verylow` this gave only the whitespace errors and other style issues. As a user, I would prefer to be told about issues in the codebase that are close to, or suggestive of logic bugs at low strictness levels. Style seems like a low priority compared to functionality.

**Comment by carlio** [comment]
This is the thing - I consider logic errors to be higher priority too, which is why they're in higher priority settings! `verylow` is really just a kind of cursory check rather than anything in depth, the idea was that `medium` would be the "maximum utility minimum noise" type setting. You can always configure with profiles (http://prospector.landscape.io/en/master/profiles.html).
