### ISSUE TITLE
Silent exit code 2 for unavailable tools

### ISSUE THREAD

**Issue by jquast** [landscapeio/prospector#162]
When ``landscape.yml`` or ``prospector.yaml`` declares to run a tool that is not installed, nothing happens and exit code 2 is returned by prospector.

Only when the ``--direct-tool-stdout`` argument is used, the true reason may be revealed, transcript follows:

```
$ cat .landscape.yml
frosted:
    run: true
$ cat xyz.py
bad syntax
$ prospector xyz.py
$ echo $?
2
$ prospector --direct-tool-stdout

Cannot run tool frosted as support was not installed.
Please install by running 'pip install prospector[with_frosted]'

$ prospector --version
prospector 0.11.7
$ python -V
Python 3.5.1
```

Suggest such output is revealed without use of ``--direct-tool-stdout``

**Comment by carlio** [comment]
Oops that used to happen but I must have accidentally squashed it when trying to hide extraneous pylint output. I'll restore it, thanks!

**Comment by carlio** [comment]
Ok fixed in develop branch, will make it into next release shortly

**Comment by carlio** [comment]
@jquast actually I discovered another issue here, turns out that pyroma 1.8.3 has a strange `import loggings` line which causes it to break and prospector was pinned to `<2.0`. You may run into further pyroma errors unless you manually upgrade pyroma. I'll fix the `setup.py` to not be so restrictive too.
