### ISSUE TITLE
test-warnings should be true by default

### ISSUE THREAD

**Issue by karyon** [landscapeio/prospector#164]
i just learned that tests are excluded by default. this came as a complete surprise. to me, testing code should hold to some quality standards just like production code. there might be some lints that are not as valid in testing code, such as accessing private variables, but i don't see a good reason to completely exclude testing code from linting.

in fact, when enabling it, i found a test that wasn't actually testing anything because it didn't use a variable that it should have used.

**Comment by carlio** [comment]
To be honest this is entirely a personal thing - I generally am a little more lax with what can and can't go into tests so don't mind if they are a little more flexible. I like to make sure code is tested rather than restricting what code I can test due to coding styles. But it's just a matter of taste, that's why the `--test-warnings` flag (currently broken oops see #151) and [profiles](http://prospector.landscape.io/en/master/profiles.html) exist. I made the tool to my opinions but everyone has different opinions, hence the configurability.
