### ISSUE TITLE
zeror exit not working

### ISSUE THREAD

**Issue by vim345** [landscapeio/prospector#177]
I was trying to run prospector on a git pre-push hook. That's why I needed to access the status code on exit using -0 or --zero-exit parameter. However, even when I run prospector it always returns code 0, even when there's an error.

I get the same error using prospector 0.12 both in Mac OS X and Centos 7:

```
└→[✓] ⚑⚑⚑ prospector -0 -P .prospector.yaml --profile-path . common/api_client.py
Messages
========

common/api_client.py
  Line: 20
    pep8: E302 / expected 2 blank lines, found 1 (col 1)



Check Information
=================
         Started: 2016-07-14 16:15:46.705234
        Finished: 2016-07-14 16:15:47.094318
      Time Taken: 0.39 seconds
       Formatter: grouped
        Profiles: .prospector.yaml, full_pep8, strictness_medium, strictness_high, strictness_veryhigh, no_doc_warnings, no_member_warnings, no_test_warnings
      Strictness: from profile
  Libraries Used: 
       Tools Run: dodgy, pep8, profile-validator, pyflakes, pylint
  Messages Found: 1

┌ 16:15:47 - (MyBranch|✚5) vim345@desktop - [~/data/etls]
└→[✓] ⚑⚑⚑ echo $?
0
```

**Comment by carlio** [comment]
@vim345 That is the intended behaviour. I just checked and I think the problem is that the 'help' text for that option is not clear.

`--zero-exit` or `-0` means "always exit with 0". The idea is that 0 means 'prospector ran fine' and anything else means 'prospector had an internal error'. That's more useful in some CI tools.

The default behaviour is to return 0 if no errors are found or 1 if errors are found. So if you just remove that `-0` flag you will get the behaviour you want, I think.

I'll update the help text to be more clear!

**Comment by vim345** [comment]
@carlio thanks man. I just verified it and noticed I get 0 on error. I'm not too sure why I didn't try it without -0 option. I think it would be a great idea to update the description though.
